import streamlit as st
import pandas as pd
import requests
import io
import ast
import warnings
import altair as alt
import os
from euroleague_api.game_stats import GameStats

# Suppress warnings
warnings.filterwarnings("ignore")

@st.cache_data
def load_data():
    try:
        p_df = pd.read_csv("data/players.csv")
        c_df = pd.read_csv("data/coaches.csv")
        return p_df, c_df
    except FileNotFoundError:
        return pd.DataFrame(), pd.DataFrame()

# ==========================================
# 2. IMPORT LOGIC
# ==========================================
def parse_ai_data(text_input):
    """Parses the python list string and populates session state."""
    try:
        data = ast.literal_eval(text_input)
        s_count = 1
        b_count = 1
        
        for player in data:
            name = player['name']
            role = player['role']
            score = player['displayed_score']
            key_suffix = None
            
            if role == "Captain":
                key_suffix = "capt"
            elif role == "Starter":
                if s_count <= 4: key_suffix = f"s{s_count}"; s_count += 1
                elif s_count == 5: key_suffix = "s6"; s_count += 1
            elif role == "Bench":
                if b_count <= 4: key_suffix = f"b{b_count}"; b_count += 1
            elif role == "Coach":
                st.session_state["name_hc"] = name
                st.session_state["p_hc"] = (score is None)
                st.session_state["s_hc"] = float(score) if score is not None else 0.0
                continue

            if key_suffix:
                st.session_state[f"name_{key_suffix}"] = name
                st.session_state[f"p_{key_suffix}"] = (score is None)
                st.session_state[f"s_{key_suffix}"] = float(score) if score is not None else 0.0
                    
        st.sidebar.success("✅ Team Imported Successfully!")
        
    except Exception as e:
        st.sidebar.error(f"❌ Error parsing data: {e}")

def get_jersey_code(csv_code):
    """Maps CSV team codes to your specific image filenames."""
    # CSV Code (Upper) -> Image Code (Lower)
    mapping = {
        "FNB": "fbb",  # Fenerbahce
        "FCB": "bar",  # Barcelona
        "MAC": "mta",  # Maccabi
        "PRS": "pbb",  # Paris
        "VAL": "vbc",  # Valencia
        "CZT": "czv",  # Zvezda
        "RMB": "rmb",  # Real Madrid
        "PAO": "pao",  # Panathinaikos
        "OLY": "oly",  # Olympiacos
        "ASM": "asm",  # Monaco
        "ASV": "asv",  # Asvel
        "BAY": "bay",  # Bayern
        "BKN": "bkn",  # Baskonia
        "DUB": "dub",  # Dubai (if applicable)
        "EFS": "efs",  # Efes
        "HTA": "hta",  # Hapoel (if applicable)
        "MIL": "mil",  # Milano
        "PAR": "par",  # Partizan
        "VIR": "vir",  # Virtus
        "ZAL": "zal"   # Zalgiris
    }
    # Return mapped code or default to lowercase version of the input
    return mapping.get(csv_code, csv_code.lower())

# ==========================================
# 3. UI LAYOUT
# ==========================================

st.set_page_config(page_title="Fantasy Credit Calculator", layout="wide")
st.title("Euroleague Fantasy Credit Change Calculator")

# --- SIDEBAR ---
with st.sidebar:
    st.header("📥 Import Team with AI")
    st.markdown("Paste the list generated by your LLM:")
    ai_input = st.text_area("Paste 'my_team_data' here:", height=150)
    if st.button("Fill Team Form"):
        if ai_input:
            parse_ai_data(ai_input)

# --- LOAD DATA ---
players_df, coaches_df = load_data()

if players_df.empty or coaches_df.empty:
    st.warning("⚠️ Data missing. Click 'Force Database Update' in sidebar.")
else:
    player_list = sorted(players_df['Player'].astype(str).tolist())
    coach_list = sorted(coaches_df['Coach'].astype(str).tolist())
    
    # Create Dictionaries for Price AND Team
    price_dict = players_df.set_index('Player')['Price'].to_dict()
    price_dict.update(coaches_df.set_index('Coach')['Price'].to_dict())
    
    # NEW: Team Dictionary (Name -> Team Code)
    team_dict = players_df.set_index('Player')['Team'].to_dict()
    team_dict.update(coaches_df.set_index('Coach')['Team'].to_dict())

    # --- TABS LAYOUT ---
    tab_input, tab_results, tab_help = st.tabs(["📝 Team Input", "📊 Results & Analysis", "ℹ️ AI Prompt & Help"])

    # ==========================
    # TAB 1: INPUTS
    # ==========================
    with tab_input:
        st.subheader("Build Your Lineup")
        col1, col2 = st.columns(2)
        team_data_temp = []

        def input_row(label, role, key, col, is_coach=False):
            with col:
                c0, c1, c2, c3 = st.columns([0.6, 2.5, 1.0, 0.8], vertical_alignment="bottom")
                
                # 1. Selector
                name = c1.selectbox(label, coach_list if is_coach else player_list, key=f"name_{key}", index=None, placeholder="Select...")
                
                # 2. Image Logic (UPDATED PATHS)
                if name:
                    # Get the raw CSV team code (e.g., "FNB")
                    csv_team_code = team_dict.get(name, "UNK")
                    
                    # Convert to your image filename format (e.g., "fbb")
                    img_code = get_jersey_code(csv_team_code)
                    
                    if is_coach:
                        # Path: jerseys/coaches/coach_OLY.png
                        image_path = f"jerseys/coaches/coach_{img_code}.png"
                    else:
                        # Path: jerseys/jersey/jersey_OLY.png
                        image_path = f"jerseys/players/jersey_{img_code}.png"
                    
                    if os.path.exists(image_path):
                        c0.image(image_path, width=70)
                    else:
                        c0.warning("?")
                
                # 3. Score
                score = c2.number_input("Score", value=0.0, step=1.0, key=f"s_{key}", label_visibility="collapsed")
                pending = c3.checkbox("T2", key=f"p_{key}", help="Pending Game")
                
                if name:
                    team_data_temp.append({
                        "name": name, "role": role, "displayed_score": None if pending else score
                    })

        with col1:
            st.info("##### Starters")
            input_row("👑 Captain (x2)", "Captain", "capt", col1)
            input_row("Starter 1", "Starter", "s1", col1)
            input_row("Starter 2", "Starter", "s2", col1)
            input_row("Starter 3", "Starter", "s3", col1)
            input_row("Starter 4", "Starter", "s4", col1)
            input_row("6th Man (100%)", "Starter", "s6", col1)

        with col2:
            st.warning("##### Bench & Coach (Input points as displayed (50%), not the actual values)")
            input_row("Bench 1", "Bench", "b1", col2)
            input_row("Bench 2", "Bench", "b2", col2)
            input_row("Bench 3", "Bench", "b3", col2)
            input_row("Bench 4", "Bench", "b4", col2)
            input_row("👔 Head Coach", "Coach", "hc", col2, is_coach=True)

        st.divider()

        # Calculate Button
        if st.button("Calculate Credit Change", type="primary", use_container_width=True):
            if not team_data_temp:
                st.error("Select at least one player.")
            else:
                results = []
                total_change = 0.0
                
                for p in team_data_temp:
                    name = p['name']
                    role = p['role']
                    d_score = p['displayed_score']
                    price = price_dict.get(name, 0.0)
                    
                    if d_score is None:
                        results.append({"Name": name, "Role": role, "Real Score": "Pending", "Price": price, "Change": 0.0})
                        continue
                    
                    if role == "Captain": n_score = d_score / 2
                    elif role == "Bench": n_score = d_score * 2
                    else: n_score = d_score
                    
                    if role == "Coach":
                        raw_change = round(((n_score - price) / 40), 1)
                    else:
                        break_even = price * 1.1
                        raw_change = round(((n_score - break_even) / 25), 1)
                    
                    # Min Price Rule (4.0)
                    potential_new = price + raw_change
                    if potential_new < 4.0:
                        final_change = round(4.0 - price, 1)
                    else:
                        final_change = raw_change

                    total_change += final_change
                    results.append({"Name": name, "Role": role, "Real Score": n_score, "Price": price, "Change": final_change})

                # SAVE TO SESSION STATE
                st.session_state['results_df'] = pd.DataFrame(results)
                st.session_state['total_change'] = total_change
                st.session_state['has_results'] = True
                
                # Success message in Tab 1
                st.success(f"Calculation Complete! Total Change: {total_change:+.1f}. Check the 'Results' tab.")

    # ==========================
    # TAB 2: RESULTS
    # ==========================
    with tab_results:
        if st.session_state.get('has_results', False):
            res_df = st.session_state['results_df']
            total = st.session_state['total_change']
            
            # 1. Total Metric
            delta_color = "normal" if total == 0 else ("inverse" if total < 0 else "normal")
            st.metric(label="TOTAL TEAM CREDIT CHANGE", value=f"{total:+.1f}", delta=f"{total:+.1f}", delta_color=delta_color)
            
            st.divider()

            # 2. Horizontal Bar Chart
            st.subheader("📊 Price Change Breakdown")
            
            chart_df = res_df.copy()
            
            # --- CHART DEFINITION ---
            base = alt.Chart(chart_df).encode(
                y=alt.Y('Name', 
                        sort=alt.EncodingSortField(field="Change", order="descending"), 
                        title=None)
            )

            bars = base.mark_bar().encode(
                x=alt.X('Change', title='Credit Change', axis=alt.Axis(format='+.1f', tickCount=10)),
                color=alt.Color('Change', scale=alt.Scale(scheme='redyellowgreen', domainMid=0, reverse=False), legend=None),
                tooltip=['Name', 'Change', 'Role', 'Price']
            )

            text_pos = base.transform_filter(alt.datum.Change > 0).mark_text(
                align='left', baseline='middle', dx=5, color='black'
            ).encode(x=alt.X('Change'), text=alt.Text('Change', format='+.1f'))

            text_neg = base.transform_filter(alt.datum.Change < 0).mark_text(
                align='right', baseline='middle', dx=-5, color='black'
            ).encode(x=alt.X('Change'), text=alt.Text('Change', format='+.1f'))

            text_zero_outline = base.transform_filter(alt.datum.Change == 0).mark_text(
                text='0.0', fontSize=16, fontWeight='bold', stroke='black', strokeWidth=4, align='left', baseline='middle', dx=5
            ).encode(x=alt.X('Change'))

            text_zero_fill = base.transform_filter(alt.datum.Change == 0).mark_text(
                text='0.0', fontSize=16, fontWeight='bold', color='white', align='left', baseline='middle', dx=5
            ).encode(x=alt.X('Change'))

            chart = (bars + text_pos + text_neg + text_zero_outline + text_zero_fill).properties(height=500)
            st.altair_chart(chart, use_container_width=True)

            # 3. Detailed Table
            st.subheader("📋 Detailed Data")
            
            def safe_fmt(val, fmt_str):
                try:
                    return fmt_str.format(float(val))
                except (ValueError, TypeError):
                    return str(val)

            st.dataframe(
                res_df.style.format({
                    "Change": lambda x: safe_fmt(x, "{:+.1f}"),
                    "Real Score": lambda x: safe_fmt(x, "{:.1f}"),
                    "Price": "{:.1f}"
                }),
                use_container_width=True,
                height=(len(res_df) * 35) + 38,
                hide_index=True
            )
            
        else:
            st.info("Please calculate your team's score in the 'Team Input' tab first.")

    # ==========================
    # TAB 3: AI PROMPT & HELP
    # ==========================
    with tab_help:
        st.header("How to Automate Your Team Import")
        st.markdown("""
        **Step 1:** Take a screenshot of your fantasy team.
                    
        **Step 2:** Upload it to ChatGPT, Claude, or Gemini.
                    
        **Step 3:** Copy the prompt below and paste it with your image.
                    
        **Step 4:** Copy the code block the AI gives you and paste it into the **Sidebar**.
        """)
        
        st.divider()
        
        st.subheader("The Prompt to Copy")
        
        st.markdown(
            "**Reference Link:**    [Open Player List (Pastebin)](https://pastebin.com/TxsreteU)", 
            help="Click to open the list of names in your browser."
        )
        
        st.code("""
**Role:** You are a specialized OCR and data extraction assistant for EuroLeague Fantasy Basketball.

**Task:** Extract the team data from the attached image into a raw Python list of dictionaries.

### 1. VISUAL LAYOUT & ROLE MAPPING RULES
* **Top Half (Basketball Court):** The 5 players physically on the court are **"Starter"**.
    * *Exception:* If a player has a **'C' badge** (usually yellow/green) next to them, their role is **"Captain"**.
* **Bottom Left (Labeled "6th"):** This player is the 6th Man. Map their role to **"Starter"**.
* **Bottom Left (Labeled "HC" / Suit Icon):** This is the Head Coach. Map their role to **"Coach"**.
* **Bottom Right (Purple Box / Labeled "Bench"):** These 4 players are the **"Bench"**.

### 2. SPELLING & IDENTITY RULES
* **CRITICAL:** You must match the names found in the image to the **EXACT spelling** provided in the "Reference List" below.
* **Do Not Autocorrect:** Use the specific spelling from the list even if it looks grammatically incorrect (e.g., use "Horton Tucker Talen" without hyphens if the list says so; use "Taylor Kameron" instead of "Kamar").
* **Visual Disambiguation (CRITICAL):** If the OCR detects a name that matches multiple entries in the list (e.g., "Jones", "Taylor", "Brown"), you **MUST** look at the player's jersey color/logo in the image to select the correct specific player from the list.
    * *Red/White Stripe* = Olympiacos (OLY) -> e.g., Jones Tyrique, Vezenkov Sasha
    * *Orange* = Valencia (VBC) -> e.g., Taylor Kameron, Ojeleye Semi
    * *Dark Blue/Black* = Anadolu Efes (EFS) / Paris (PAR) / Partizan (PAR) -> e.g., Jones Carlik, Lundberg Iffe
    * *Yellow* = Maccabi (MTA) / Fenerbahce (FBB) -> e.g., Baldwin IV Wade, Colson Bonzie
    * *Blue/Red* = Barcelona (BAR) / Baskonia (BKN)

### 3. DATA EXTRACTION
* **displayed_score:** Extract the number exactly as shown (as a float). 
    * If the score is pending (e.g., "T2", "-", or empty), return `None`.

### 4. OUTPUT FORMAT & EXAMPLES
Provide **ONLY** a raw Python list of dictionaries. No markdown formatting (like ```json), no conversational text.

**Required JSON Structure:**
[
  {"name": "Exact Name From List", "role": "RoleString", "displayed_score": FloatOrNone},
  ...
]

**Specific Role Examples:**
* **Captain:** `{"name": "Vezenkov Sasha", "role": "Captain", "displayed_score": 55.0}`
* **Starter (Court & 6th Man):** `{"name": "Kabengele Mfiondu", "role": "Starter", "displayed_score": 35.2}`
* **Bench:** `{"name": "Clyburn Will", "role": "Bench", "displayed_score": 4.0}`
* **Coach:** `{"name": "Laso Pablo", "role": "Coach", "displayed_score": 25.0}`

### 5. REFERENCE LIST (Source of Truth)
Player,Team
Vezenkov Sasha,OLY
James Mike,ASM
Francisco Sylvain,ZAL
Bryant Elijah,HTA
Milutinov Nikola,OLY
Moneke Chima,CZT
Nunn Kendrick,PAO
Kabengele Mfiondu,DUB
Baldwin IV Wade,FNB
Shengelia Tornike,FCB
Tavares Walter,RMB
Wright IV McKinley,DUB
Petrusev Filip,DUB
Punter Kevin,FCB
Campazzo Facundo,RMB
Hifi Nadir,PRS
Hoard Jaylen,MAC
Lyles Trey,RMB
Oturu Dan,HTA
Jones Tyrique,OLY
Wright Moses,ZAL
Montero Jean,VAL
Leday Zach,MIL
Nwora Jordan,CZT
Clyburn Will,FCB
Hernangomez Juancho,PAO
De Colo Nando,FNB
Mirotic Nikola,ASM
Sloukas Kostas,PAO
Diallo Alpha,ASM
Taylor Kameron,VAL
Horton Tucker Talen,FNB
Miller-McIntyre Codi,CZT
Sorkin Roman,MAC
Walker IV Lonnie,MAC
Lessort Mathias,PAO
Luwawu-Cabarrot Timothe,BKN
Shields Shavon,MIL
Maledon Theo,RMB
Larkin Shane,EFS
Tubelis Azuolas,ZAL
Dorsey Tyler,OLY
Jones Carlik,PAR
Robinson Justin,PRS
Hezonja Mario,RMB
Nebo Josh,MIL
Bacon Dwayne,DUB
Guduric Marko,MIL
Hall Donta,OLY
Bonga Isaac,PAR
Theis Daniel,ASM
Leaf TJ,MAC
Micic Vasilije,HTA
Musa Dzanan,DUB
Thompson Darius,VAL
Forrest Trent,BKN
Edwards Carsen,VIR
Obst Andreas,BAY
Okobo Elie,ASM
Butler Jared,CZT
Angola Braian,ASV
Watson Glynn,ASV
Weiler-Babb Nick,EFS
Brown Sterling,PAR
Holmes Richaun,PAO
Jones Chris,HTA
Payne Cameron,PAR
Rhoden Jared,PRS
Lucic Vladimir,BAY
Morgan Matthew,VIR
Motley Johnathan,HTA
Osman Cedi,PAO
Williams-Goss Nigel,ZAL
Dimitrijevic Neno,BAY
Poirier Vincent,EFS
Bolomboy Joel,CZT
Satoransky Tomas,FCB
Fernando Bruno,PAR
Jokubaitis Rokas,BAY
Shorts TJ,PAO
Brissett Oshae,MAC
Omoruyi Eugene,BKN
Evans Keenan,OLY
Melli Nicolo,FNB
Blakeney Antonio,HTA
Booker Devin,MIL
Izundu Ebuka,CZT
Brooks Armoni,MIL
Lundberg Iffe,MAC
Okeke Chuma,RMB
Walkup Thomas,OLY
Simmons Kobi,BKN
Reuvers Nathan,VAL
Washington Duane,PAR
Grant Jerian,PAO
Biberovic Tarik,FNB
Vildoza Luca,VIR
Bolmaro Leandro,MIL
Diallo Hamidou,BKN
Fournier Evan,OLY
Osmani Ercan,EFS
Pradilla Jaime,VAL
Vesely Jan,FCB
Dinwiddie Spencer,BAY
Ellis Quinn,MIL
Hernangomez Willy,FCB
Avramovic Aleksa,DUB
Silva Chris,FNB
Lee Saben,EFS
Niang Saliou,VIR
Ojeleye Semi,CZT
Strazel Matthew,ASM
Blatt Tamir,MAC
Sedekerskis Tadas,BKN
Alston Jr Derrick,VIR
Cordinier Isaia,EFS
Jones Kai,EFS
Diouf Mouhamet,VIR
Joseph Cory,OLY
Loyd Jordan,EFS
Caboclo Bruno,HTA
Dowtin Jr Jeffrey,MAC
Lo Maodo,ZAL
Moore Omari,VAL
Ndiaye Mbaye,ASV
Clark III Jimmy,MAC
Mike Isiaha,BAY
Colson Bonzie,FNB
Costello Matthew,VAL
Diakite Mamadi,BKN
Ryan Matt,DUB
Ward Tyson,OLY
Howard Markus,BKN
Blossomgame Jaron,ASM
Deck Gabriel,RMB
Morris Monte,OLY
Hall Devon,FNB
Laprovittola Nicolas,FCB
Stevens Lamar,PRS
Faried Kenneth,PAO
Gabriel Wenyen,BAY
Badio Brancou,VAL
Fall Moustapha,OLY
Heurtel Thomas,ASV
Milton Shake,PAR
Peters Alec,OLY
Sako Neal,VAL
Jekiri Tonye,PAR
Hayes Kevarrius,ASM
Boston Jr Brandon,FNB
Brown Lorenzo,MIL
Dozier PJ,EFS
Jessup Justinian,BAY
Kalinic Nikola,CZT
Ulanovas Edgaras,ZAL
Willis Derek,PRS
Cancar Vlatko,MIL
Malcolm Collin,HTA
Osetkowski Dylan,PAR
Yurtseven Omer,PAO
McCormack David,BAY
Ellis Boogie,DUB
Faye Mouhamed,PRS
Smailagic Alen,VIR
Brizuela Dario,FCB
Graham Devonte,CZT
Parker Jabari,PAR
Seljaas Zachary,ASV
Key Braxton,VAL
Jallow Karim,VIR
Kurucs Rodions,BKN
Samanic Luka,BKN
Voigtmann Johannes,BAY
Wilbekin Scottie,FNB
Mason Nate,DUB
Parra Joel,FCB
Rivero Jasiel,CZT
Da Silva Oscar,BAY
Dokossi Allan,PRS
Radzevicius Gytis,BKN
Spagnolo Matteo,BKN
Traore Armel,ASV
Carter Tyson,CZT
Len Alex,RMB
M'Baye Amath,PRS
Motiejunas Donatas,CZT
Anderson Justin,DUB
Kamenjas Kenan,DUB
Mitoglou Konstantinos,PAO
Nedovic Nemanja,ASM
Sleva Dustin,ZAL
Pajola Alessandro,VIR
Swider Cole,EFS
Nowell Markquis,BKN
Garuba Usman,RMB
Jovic Stefan,BAY
Norris Miles,FCB
Santos Marcio,MAC
Butkevicius Arnas,ZAL
Ennis Tyler,HTA
Madar Yam,HTA
Smits Rolands,EFS
Bertans Davis,DUB
Harrison Shaquille,ASV
Diarra Aliou,VIR
Jantunen Mikael,FNB
Feliz Andres,RMB
Diop Khalifa,BKN
Taylor Brandon,VIR
Wainright Ish,HTA
Calathes Nick,PAR
Hankins Zachary,MAC
Morgan Jeremy,PRS
Odiase Tai,HTA
Bacot Jr Armando,FNB
Birch Khem,FNB
Eboua Paul,ASV
Makoundou Yoan,ASM
Ntilikina Frank,OLY
Papagiannis Georgios,EFS
Rathan-Mayes Xavier,BAY
Vautier Bastien,ASV
Brazdeikis Ignas,ZAL
Birutis Laurynas,ZAL
Dessert Brice,EFS
Armstrong Taran,DUB
Ginat Tomer,HTA
Hackett Daniel,VIR
Lopez-Arostegui Xabi,VAL
Michineau David,ASM
Puerto Josep,VAL
Beaubois Rodrigue,EFS
Sirvydis Deividas,ZAL
Abalde Alberto,RMB
Ayayi Joel,PRS
Giffey Niels,BAY
Massa Bodian,ASV
Bako Ismael,PRS
Fall Youssoupha,FCB
Happ Ethan,VAL
Mannion Niccolo,MIL
Mckissic Shaquielle,OLY
Akele Nicola,VIR
Baldwin Kamar,BAY
Zagars Arturs,FNB
Cale Myles,FCB
Hazer Sehmus,EFS
Herrera Sebastian,PRS
Hollatz Justus,BAY
Marinkovic Vanja,PAR
Papanikolaou Kostas,OLY
Toliopoulos Vassilis,PAO
Cavaliere Leopold,PRS
Iroegbu Ike,VAL
Dunston Bryant,MIL
Frisch Clement,BKN
Ferrari Francesco,VIR
Lakic Arijan,PAR
Ajinca Melvin,ASV
Dibartolomeo John,MAC
Jackson Edwin,ASV
Jaiteh Mam,DUB
Nunez Juan,FCB
Rayman William,MAC
Ricci Giampaolo,MIL
Abass Awudu,DUB
Birsen Metecan,FNB
Giedraitis Dovydas,ZAL
Hommes Daulton,PRS
Ouattara Yakuba,PRS
Trifunovic Uros,MAC
Rogkavopoulos Nikolaos,PAO
Bitim Onuralp,FNB
Kondic Kosta,DUB
Prepelic Klemen,DUB
Procida Gabriele,RMB
Accorsi Matteo,VIR
Almansa Izan,RMB
Stojkovic Lazar,CZT
Andjusic Danilo,DUB
Antetokounmpo Kostas,OLY
Tarpey Terry,ASM
Timor Bar,HTA
Tonut Stefano,MIL
Bango Jilson,FNB
Begarin Juhann,ASM
Villar Rafa,BKN
Blayzer Oz,HTA
Bosnjakovic Mitar,PAR
Yildizli Burakcan,EFS
Yilmaz Erkan,EFS
Ziv Iftach,HTA
Rubstavicius Mantas,ZAL
Canaan Isaiah,CZT
Atamna Adam,ASV
Canka Abramo,VIR
Joksimovic Stefan,BKN
Nogues Isaac,VAL
Nedeljkovic Aleksej,CZT
Dos Santos Yago,CZT
Dangubic Nemanja,DUB
Grinvalds Gunars,RMB
Davidovac Dejan,CZT
Gur Lavi,MAC
Muurinen Miikka,PAR
De Larrea Sergio,VAL
Ngouama Mehdy,ASV
Sanli Sertac,DUB
Keita Sayon,FCB
Wade Marvyn,ASV
Diop Ousmane,MIL
Mikalauskas Kajus,ZAL
Tote Leonardo,MIL
Dobric Ognjen,CZT
Hrabar Vit,BKN
Radanov Aleksa,BAY
Eksioglu Mert,FNB
Kusturica Nikola,FCB
Flaccadori Diego,MIL
Grigonis Marius,PAO
Harris Elias,BAY
Ilic Dalibor,CZT
Kalaitzakis Panagiotis,PAO
Kouzeloglou Ioannis,PAO
Kramer David,RMB
Kratzer Leon,BAY
Larentzakis Giannoulis,OLY
Lighty David,ASV
Llull Sergio,RMB
Mahmutoglu Melih,FNB
Marcos Juani,FCB
Mestoglu Yigit Hamza,FNB
Miljenovic Stefan,CZT
Moungalla Ilian,PRS
Mutaf David,EFS
Nakic Mario,PAR
Netzipoglou Omiros,OLY
Palatin Guy,HTA
Plavsic Uros,CZT
Pokusevski Aleksej,PAR
Radosic Ognjen,CZT
Ravena Thirdy,DUB
Samodurov Alexandros,PAO
Segev Itay,HTA
Sestina Nathan,MIL
Shahrvin Enzo,PRS
Sima Yankuba,VAL
                
""", language="text")