import streamlit as st
import pandas as pd
import requests
import io
import ast
import warnings
import altair as alt
import os
from euroleague_api.game_stats import GameStats

# Suppress warnings
warnings.filterwarnings("ignore")

@st.cache_data
def load_data():
    try:
        p_df = pd.read_csv("data/players.csv")
        c_df = pd.read_csv("data/coaches.csv")
        return p_df, c_df
    except FileNotFoundError:
        return pd.DataFrame(), pd.DataFrame()

# ==========================================
# 2. IMPORT LOGIC
# ==========================================
def parse_ai_data(text_input):
    """Parses the python list string and populates session state."""
    try:
        data = ast.literal_eval(text_input)
        s_count = 1
        b_count = 1
        
        for player in data:
            name = player['name']
            role = player['role']
            score = player['displayed_score']
            key_suffix = None
            
            if role == "Captain":
                key_suffix = "capt"
            elif role == "Starter":
                if s_count <= 4: key_suffix = f"s{s_count}"; s_count += 1
                elif s_count == 5: key_suffix = "s6"; s_count += 1
            elif role == "Bench":
                if b_count <= 4: key_suffix = f"b{b_count}"; b_count += 1
            elif role == "Coach":
                st.session_state["name_hc"] = name
                st.session_state["p_hc"] = (score is None)
                st.session_state["s_hc"] = float(score) if score is not None else 0.0
                continue

            if key_suffix:
                st.session_state[f"name_{key_suffix}"] = name
                st.session_state[f"p_{key_suffix}"] = (score is None)
                st.session_state[f"s_{key_suffix}"] = float(score) if score is not None else 0.0
                    
        st.sidebar.success("✅ Team Imported Successfully!")
        
    except Exception as e:
        st.sidebar.error(f"❌ Error parsing data: {e}")

def get_jersey_code(csv_code):
    """Maps CSV team codes to your specific image filenames."""
    # CSV Code (Upper) -> Image Code (Lower)
    mapping = {
        "FNB": "fbb",  # Fenerbahce
        "FCB": "bar",  # Barcelona
        "MAC": "mta",  # Maccabi
        "PRS": "pbb",  # Paris
        "VAL": "vbc",  # Valencia
        "CZT": "czv",  # Zvezda
        "RMB": "rmb",  # Real Madrid
        "PAO": "pao",  # Panathinaikos
        "OLY": "oly",  # Olympiacos
        "ASM": "asm",  # Monaco
        "ASV": "asv",  # Asvel
        "BAY": "bay",  # Bayern
        "BKN": "bkn",  # Baskonia
        "DUB": "dub",  # Dubai (if applicable)
        "EFS": "efs",  # Efes
        "HTA": "hta",  # Hapoel (if applicable)
        "MIL": "mil",  # Milano
        "PAR": "par",  # Partizan
        "VIR": "vir",  # Virtus
        "ZAL": "zal"   # Zalgiris
    }
    # Return mapped code or default to lowercase version of the input
    return mapping.get(csv_code, csv_code.lower())

# ==========================================
# 3. UI LAYOUT
# ==========================================

st.set_page_config(page_title="Fantasy Credit Calculator", layout="wide")
st.title("Euroleague Fantasy Credit Change Calculator")

# --- SIDEBAR ---
with st.sidebar:
    st.header("📥 Import Team with AI")
    st.markdown("Paste the list generated by your LLM:")
    ai_input = st.text_area("Paste 'my_team_data' here:", height=150)
    if st.button("Fill Team Form"):
        if ai_input:
            parse_ai_data(ai_input)

# --- LOAD DATA ---
players_df, coaches_df = load_data()

if players_df.empty or coaches_df.empty:
    st.warning("⚠️ Data missing. Click 'Force Database Update' in sidebar.")
else:
    player_list = sorted(players_df['Player'].astype(str).tolist())
    coach_list = sorted(coaches_df['Coach'].astype(str).tolist())
    
    # Create Dictionaries for Price AND Team
    price_dict = players_df.set_index('Player')['Price'].to_dict()
    price_dict.update(coaches_df.set_index('Coach')['Price'].to_dict())
    
    # NEW: Team Dictionary (Name -> Team Code)
    team_dict = players_df.set_index('Player')['Team'].to_dict()
    team_dict.update(coaches_df.set_index('Coach')['Team'].to_dict())

    # --- TABS LAYOUT ---
    tab_input, tab_results, tab_help = st.tabs(["📝 Team Input", "📊 Results & Analysis", "ℹ️ AI Prompt & Help"])

    # ==========================
    # TAB 1: INPUTS
    # ==========================
    with tab_input:
        st.subheader("Build Your Lineup")
        col1, col2 = st.columns(2)
        team_data_temp = []

        def input_row(label, role, key, col, is_coach=False):
            with col:
                c0, c1, c2, c3 = st.columns([0.6, 2.5, 1.0, 0.8], vertical_alignment="bottom")
                
                # 1. Selector
                name = c1.selectbox(label, coach_list if is_coach else player_list, key=f"name_{key}", index=None, placeholder="Select...")
                
                # 2. Image Logic (UPDATED PATHS)
                if name:
                    # Get the raw CSV team code (e.g., "FNB")
                    csv_team_code = team_dict.get(name, "UNK")
                    
                    # Convert to your image filename format (e.g., "fbb")
                    img_code = get_jersey_code(csv_team_code)
                    
                    if is_coach:
                        # Path: jerseys/coaches/coach_OLY.png
                        image_path = f"jerseys/coaches/coach_{img_code}.png"
                    else:
                        # Path: jerseys/jersey/jersey_OLY.png
                        image_path = f"jerseys/players/jersey_{img_code}.png"
                    
                    if os.path.exists(image_path):
                        c0.image(image_path, width=70)
                    else:
                        c0.warning("?")
                
                # 3. Score
                score = c2.number_input("Score", value=0.0, step=1.0, key=f"s_{key}", label_visibility="collapsed")
                pending = c3.checkbox("T2", key=f"p_{key}", help="Pending Game")
                
                if name:
                    team_data_temp.append({
                        "name": name, "role": role, "displayed_score": None if pending else score
                    })

        with col1:
            st.info("##### Starters")
            input_row("👑 Captain (x2)", "Captain", "capt", col1)
            input_row("Starter 1", "Starter", "s1", col1)
            input_row("Starter 2", "Starter", "s2", col1)
            input_row("Starter 3", "Starter", "s3", col1)
            input_row("Starter 4", "Starter", "s4", col1)
            input_row("6th Man (100%)", "Starter", "s6", col1)

        with col2:
            st.warning("##### Bench & Coach (Input points as displayed (50%), not the actual values)")
            input_row("Bench 1", "Bench", "b1", col2)
            input_row("Bench 2", "Bench", "b2", col2)
            input_row("Bench 3", "Bench", "b3", col2)
            input_row("Bench 4", "Bench", "b4", col2)
            input_row("👔 Head Coach", "Coach", "hc", col2, is_coach=True)

        st.divider()

        # Calculate Button
        if st.button("Calculate Credit Change", type="primary", use_container_width=True):
            if not team_data_temp:
                st.error("Select at least one player.")
            else:
                results = []
                total_change = 0.0
                
                for p in team_data_temp:
                    name = p['name']
                    role = p['role']
                    d_score = p['displayed_score']
                    price = price_dict.get(name, 0.0)
                    
                    if d_score is None:
                        results.append({"Name": name, "Role": role, "Real Score": "Pending", "Price": price, "Change": 0.0})
                        continue
                    
                    if role == "Captain": n_score = d_score / 2
                    elif role == "Bench": n_score = d_score * 2
                    else: n_score = d_score
                    
                    if role == "Coach":
                        raw_change = round(((n_score - price) / 40), 1)
                    else:
                        break_even = price * 1.1
                        raw_change = round(((n_score - break_even) / 25), 1)
                    
                    # Min Price Rule (4.0)
                    potential_new = price + raw_change
                    if potential_new < 4.0:
                        final_change = round(4.0 - price, 1)
                    else:
                        final_change = raw_change

                    total_change += final_change
                    results.append({"Name": name, "Role": role, "Real Score": n_score, "Price": price, "Change": final_change})

                # SAVE TO SESSION STATE
                st.session_state['results_df'] = pd.DataFrame(results)
                st.session_state['total_change'] = total_change
                st.session_state['has_results'] = True
                
                # Success message in Tab 1
                st.success(f"Calculation Complete! Total Change: {total_change:+.1f}. Check the 'Results' tab.")

    # ==========================
    # TAB 2: RESULTS
    # ==========================
    with tab_results:
        if st.session_state.get('has_results', False):
            res_df = st.session_state['results_df']
            total = st.session_state['total_change']
            
            # 1. Total Metric
            delta_color = "normal" if total == 0 else ("inverse" if total < 0 else "normal")
            st.metric(label="TOTAL TEAM CREDIT CHANGE", value=f"{total:+.1f}", delta=f"{total:+.1f}", delta_color=delta_color)
            
            st.divider()

            # 2. Horizontal Bar Chart
            st.subheader("📊 Price Change Breakdown")
            
            chart_df = res_df.copy()
            
            # --- CHART DEFINITION ---
            base = alt.Chart(chart_df).encode(
                y=alt.Y('Name', 
                        sort=alt.EncodingSortField(field="Change", order="descending"), 
                        title=None)
            )

            bars = base.mark_bar().encode(
                x=alt.X('Change', title='Credit Change', axis=alt.Axis(format='+.1f', tickCount=10)),
                color=alt.Color('Change', scale=alt.Scale(scheme='redyellowgreen', domainMid=0, reverse=False), legend=None),
                tooltip=['Name', 'Change', 'Role', 'Price']
            )

            text_pos = base.transform_filter(alt.datum.Change > 0).mark_text(
                align='left', baseline='middle', dx=5, color='black'
            ).encode(x=alt.X('Change'), text=alt.Text('Change', format='+.1f'))

            text_neg = base.transform_filter(alt.datum.Change < 0).mark_text(
                align='right', baseline='middle', dx=-5, color='black'
            ).encode(x=alt.X('Change'), text=alt.Text('Change', format='+.1f'))

            text_zero_outline = base.transform_filter(alt.datum.Change == 0).mark_text(
                text='0.0', fontSize=16, fontWeight='bold', stroke='black', strokeWidth=4, align='left', baseline='middle', dx=5
            ).encode(x=alt.X('Change'))

            text_zero_fill = base.transform_filter(alt.datum.Change == 0).mark_text(
                text='0.0', fontSize=16, fontWeight='bold', color='white', align='left', baseline='middle', dx=5
            ).encode(x=alt.X('Change'))

            chart = (bars + text_pos + text_neg + text_zero_outline + text_zero_fill).properties(height=500)
            st.altair_chart(chart, use_container_width=True)

            # 3. Detailed Table
            st.subheader("📋 Detailed Data")
            
            def safe_fmt(val, fmt_str):
                try:
                    return fmt_str.format(float(val))
                except (ValueError, TypeError):
                    return str(val)

            st.dataframe(
                res_df.style.format({
                    "Change": lambda x: safe_fmt(x, "{:+.1f}"),
                    "Real Score": lambda x: safe_fmt(x, "{:.1f}"),
                    "Price": "{:.1f}"
                }),
                use_container_width=True,
                height=(len(res_df) * 35) + 38,
                hide_index=True
            )
            
        else:
            st.info("Please calculate your team's score in the 'Team Input' tab first.")

    # ==========================
    # TAB 3: AI PROMPT & HELP
    # ==========================
    with tab_help:
        st.header("How to Automate Your Team Import")
        st.markdown("""
        **Step 1:** Take a screenshot of your fantasy team.
                    
        **Step 2:** Upload it to ChatGPT, Claude, or Gemini.
                    
        **Step 3:** Copy the prompt below and paste it with your image.
                    
        **Step 4:** Copy the code block the AI gives you and paste it into the **Sidebar**.
        """)
        
        st.divider()
        
        st.subheader("The Prompt to Copy")
        
        st.markdown(
            "**Reference Link:**    [Open Player List (Pastebin)](https://pastebin.com/TxsreteU)", 
            help="Click to open the list of names in your browser."
        )
        
        st.code("""
Please extract the fantasy basketball team data from this image and format it as a raw Python list of dictionaries.

Follow these strict formatting rules so my code can parse it:
1. Output ONLY a Python list starting with `[` and ending with `]`. Do not include variable assignments or markdown formatting.
2. Each player/coach must be a dictionary with keys: "name", "role", "displayed_score".
3. "name": Full name string (e.g., "Vezenkov Sasha").
4. "role": One of: "Captain", "Starter", "Bench", "Coach".
5. "displayed_score":
   - If numeric, use the float (e.g., 17.60).
   - If "T2"/pending, use Python `None`.
6. CRITICAL: Verify spelling against this official list: https://pastebin.com/TxsreteU

Example output:
[
    {"name": "James Mike", "role": "Captain", "displayed_score": 22.5},
    {"name": "Ataman Ergin", "role": "Coach", "displayed_score": None}
]
        """, language="text")